{
 "title": "Log Shipper",
 "description": "Statistics for vector log forwarder",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, node)"
    }
   },
   {
    "name": "component",
    "label": "component_id",
    "query": {
     "query": "label_values(vector_component_received_event_bytes_total{component_id!~\"internal_metrics|prometheus_sink\"}, component_id)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(vector_http_client_responses_total{component_id!~\"internal_metrics|prometheus_sink\"}, status)"
    }
   },
   {
    "name": "component_with_errors",
    "query": {
     "query": "label_values(vector_component_errors_total{node=~\"$node\", job=\"log-shipper-agent\", component_name=~\"$component\"}, component_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Agents number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"log-shipper-agent\"})"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (component_id, component_kind) (rate(vector_utilization{node=~\"$node\", job=\"log-shipper-agent\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ component_kind }} : {{ component_id }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vector_uptime_seconds{job=\"log-shipper-agent\"}"
    }
   ]
  },
  {
   "title": "Opened Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(vector_open_files{node=~\"$node\", job=\"log-shipper-agent\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Reloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(vector_reloaded_total{node=~\"$node\", job=\"log-shipper-agent\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Events Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Events rate (IN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (component_kind, component_id) (rate(vector_component_received_events_total{component_id=~\"$component\", job=\"log-shipper-agent\"}[$__rate_interval])) > 0",
     "legendFormat": "{{component_kind}} : {{ component_id }}"
    }
   ]
  },
  {
   "title": "Events rate (OUT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (component_kind, component_id) (rate(vector_component_sent_events_total{component_id=~\"$component\", job=\"log-shipper-agent\"}[$__rate_interval])) > 0",
     "legendFormat": "{{component_kind}} : {{ component_id }}"
    }
   ]
  },
  {
   "title": "Event Bytes rate (IN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (component_kind, component_id) (rate(vector_component_received_event_bytes_total{component_id=~\"$component\"}[$__rate_interval])) > 0",
     "legendFormat": "{{component_kind}} : {{ component_id }}"
    }
   ]
  },
  {
   "title": "Event Bytes rate (OUT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (component_kind, component_id) (rate(vector_component_sent_event_bytes_total{component_id=~\"$component\"}[$__rate_interval])) > 0",
     "legendFormat": "{{component_kind}} : {{ component_id }}"
    }
   ]
  },
  { "title": "HTTP Client Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Status [$status]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "status",
   "targets": [
    {
     "expr": "sum by (component_id, component_type, component_name) (rate(vector_http_client_responses_total{node=~\"$node\", job=\"log-shipper-agent\", status=~\"$status\"}[$__rate_interval]))",
     "legendFormat": "{{ component_name }}"
    }
   ]
  },
  { "title": "Component Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Errors [$component_with_errors]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "repeat": "component_with_errors",
   "targets": [
    {
     "expr": "sum by (component_name, error_code, error_type) (rate(vector_component_errors_total{node=~\"$node\", job=\"log-shipper-agent\", component_name=~\"$component_with_errors\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ error_code }} / {{ error_type }}"
    }
   ]
  },
  {
   "title": "Input / Output [$component]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "repeat": "component",
   "collapsed": true,
   "panels": [
    {
     "title": "Received Events",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (component_id) (increase(vector_component_received_events_total{component_id=~\"$component\", job=\"log-shipper-agent\"}[$__range])) > 0",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Sent Events",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (component_id) (increase(vector_component_sent_events_total{component_id=~\"$component\", job=\"log-shipper-agent\"}[$__range])) > 0",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (component_id) (increase(vector_component_received_event_bytes_total{component_id=~\"$component\", job=\"log-shipper-agent\"}[$__range])) > 0",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (component_id) (increase(vector_component_sent_event_bytes_total{component_id=~\"$component\", job=\"log-shipper-agent\"}[$__range])) > 0",
       "legendFormat": "{{component_id}}"
      }
     ]
    }
   ]
  }
 ]
}