{
 "title": "CIS Kubernetes Benchmark",
 "description": "CIS benchmark result from a trivy-operator",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# CIS benchmark, implemented by trivy-operator\n\nSee more information about CIS [here](https://www.cisecurity.org/benchmark/kubernetes/)"
   }
  },
  {
   "title": "Total Checks Passed",
   "type": "gauge",
   "description": "All Checks Passed",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\"} == 0)/count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Total Checks Passed",
   "type": "stat",
   "description": "All Checks Passed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\"}==0)",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Total Checks Run",
   "type": "stat",
   "description": "Total Number of All Checks Run",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\"})"
    }
   ]
  },
  {
   "title": "CRITICAL severity Checks Passed",
   "type": "gauge",
   "description": "CRITICAL severity Checks Passed",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"CRITICAL\"} == 0)/count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"CRITICAL\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "HIGH severity Checks Passed",
   "type": "gauge",
   "description": "HIGH severity Checks Passed",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"HIGH\"} == 0)/count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"HIGH\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "MEDIUM severity Checks Passed",
   "type": "gauge",
   "description": "MEDIUM severity Checks Passed",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"MEDIUM\"} == 0)/count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"MEDIUM\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "LOW severity Checks Passed",
   "type": "gauge",
   "description": "LOW severity Checks Passed",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"LOW\"} == 0)/count(deckhouse_trivy_cis_benchmark{job=\"deckhouse\",severity=\"LOW\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "CIS Benchmarking Fails",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "deckhouse_trivy_cis_benchmark{job=\"deckhouse\"} != 0"
    }
   ]
  }
 ]
}